name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ martix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ martix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: make lint